sudo: false
language: scala

scala:
  - 2.12.4
  - 2.11.12

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
